version: '3'
services:
  apache:
    container_name: xanda_apache
    image: webdevops/apache:ubuntu-16.04
    environment:
      WEB_DOCUMENT_ROOT: /var/www/public
      WEB_ALIAS_DOMAIN: xanda.localhost
      WEB_PHP_SOCKET: php-fpm:9000
    volumes: # Only shared dirs to apache (to be served)
      - ./public:/var/www/public:cached
      - ./storage:/var/www/storage:cached
    networks:
      - xanda-network
    ports:
      - "80:80"
      - "443:443"
  php-fpm:
    container_name: xanda_php
    image: jguyomard/laravel-php:7.2
    volumes:
      - ./:/var/www/
      - ./ci:/var/www/ci:cached
      - ./vendor:/var/www/vendor:delegated
      - ./storage:/var/www/storage:delegated
      - ./node_modules:/var/www/node_modules:cached
      - ~/.ssh:/root/.ssh:cached
      - ~/.composer/cache:/root/.composer/cache:delegated
    networks:
      - xanda-network
  db:
    container_name: xanda_db
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xanda
      MYSQL_USER: xanda
      MYSQL_PASSWORD: secret
    volumes:
      - xanda-data:/var/lib/mysql
    networks:
      - xanda-network
    ports:
      - "33060:3306"
networks:
  xanda-network:
    driver: "bridge"
volumes:
  xanda-data:
    driver: "local"
